---
- hosts: all
  become: yes

  vars:
    aws_region: "us-east-1"
    ec2_key_name: "vacationvibe-key"
    ec2_instance_type: "t2.micro"
    ec2_instance_count: 1
    ec2_subnet_id: "subnet-011fd6c0d3c0f2c3c"
    ec2_security_group: "sg-0d5f3f5a2e308c635"
    backend_repository: "https://github.com/Zara-Ray/VacationVibe-Backend.git"
    backend_directory: "/home/ubuntu/vacationvibe-backend"
    backend_docker_image: "vacationvibe-backend"
    frontend_repository: "https://github.com/Zara-Ray/VacationVibe-Frontend.git"
    frontend_directory: "/home/ubuntu/vacationvibe-frontend"
    load_balancer_name: "VacationVibe-LoadBalancer"
    target_group_name: "VacationVibe-TargetGroup"
    listener_protocol: "HTTP"
    listener_port: 80

  roles:
    - roles/aws
    - roles/backend
    - roles/frontend
    - roles/load_balancer
